--获取子公司的预算控制策略
CREATE PROC [dbo].[proc_czly_GetPrjCtrl](
	@FBraOffice INT=0 --为0代表获取所有的
)
AS
BEGIN
--MAKE SURE TO ADD NEW ORG
INSERT INTO CZ_BDG_COSTITEMCTRL(FBraOffice) 
SELECT FORGID FROM T_ORG_ORGANIZATIONS WHERE FORGID NOT IN (SELECT FBraOffice FROM CZ_BDG_COSTITEMCTRL)

BEGIN
IF(@FBraOffice=0) 
	SELECT * FROM CZ_BDG_COSTITEMCTRL
ELSE 
	SELECT * FROM CZ_BDG_COSTITEMCTRL WHERE FBraOffice=@FBraOffice
END

END

