--商机下推生成报价
CREATE PROC [dbo].[proc_czly_GeneSaleOffer](
	@NFID INT
)
AS
BEGIN
	
--获取编码规则
DECLARE @FBillNo VARCHAR(50)

DECLARE @prefix VARCHAR(10) --编码规则前缀
DECLARE @FRULEID VARCHAR(50)
SELECT @FRULEID=FRULEID FROM T_BAS_BILLCODERULE where FBILLFORMID='ora_CRM_SaleOffer'
SELECT @prefix=FPROJECTVALUE FROM T_BAS_BILLCODERULEENTRY WHERE FRULEID=@FRULEID AND FPROJECTTYPE=1
DECLARE @date VARCHAR(10) = LEFT(CONVERT(varchar(100), GETDATE(), 112), 6) --日期yyyyMM
SET @prefix += @date
--SELECT FFORMAT FROM T_BAS_BILLCODERULEENTRY WHERE FRULEID='5e0301cb366088' AND FPROJECTTYPE=2
DECLARE @serial_num INT
--SELECT FLENGTH FROM T_BAS_BILLCODERULEENTRY WHERE FRULEID='5e0301cb366088' AND FPROJECTTYPE=16

--获取本月本单中最大的编码
DECLARE @MaxNum INT
SELECT  @MaxNum=MAX(RIGHT(FBILLNO, 3))+1 FROM ora_CRM_SaleOffer
WHERE LEFT(RIGHT(FBILLNO, 9),4)=YEAR(GETDATE()) AND LEFT(RIGHT(FBILLNO, 5),2)=MONTH(GETDATE())
SET @MaxNum=ISNULL(@MaxNum, 1)

--SELECT @serial_num=FNUMMAX+1 FROM T_BAS_BILLCODES WHERE FRULEID=@FRULEID
--SELECT @serial_num=ISNULL(@serial_num, 1)
UPDATE T_BAS_BILLCODES SET FNUMMAX=@MaxNum WHERE FRULEID=@FRULEID
SET @FBillNo=dbo.fun_BosRnd_addSpace(@MaxNum, @prefix, '', 3) --生成编码

--SELECT @FBillNo
--生成主键
DECLARE @SFID INT = IDENT_CURRENT('Z_ora_CRM_SaleOffer') + 1
DBCC CHECKIDENT(Z_ora_CRM_SaleOffer, RESEED, @SFID)

--表头
INSERT INTO ora_CRM_SaleOffer(
	FID,FBILLNO,FDOCUMENTSTATUS,FCREATORID,FCREATEDATE,FORGID,FSRCBILLTYPE,FNICHEID,
	FCUSTNAME,FPRJNAME,FREMARKS,
	FCURRENCYID,FCURRENCYCN,FRATE,FRATETYPE,--FPAYCOND,
	FCRMHDORGID,FCRMHDDEPT,FCRMHOLDER,FCRMSN,
	FBILLSTATUS1,FPRJADRESS
)
SELECT 
	@SFID,@FBillNo,'A',FCREATORID,GETDATE(),FORGID,'ora_CRM_Niche',FBILLNO,
	FCUSTID,FPRJNAME,FREMARKS,
	FCURRENCYID,FCURRENCYCN,FRATE,FRATETYPE,
	FCRMHDORGID,FCRMHDDEPT,FCRMHOLDER,FCRMSN,
	0,FPRJADDRESS
FROM ora_CRM_Niche WHERE FID=@NFID

--产品大类表体
DECLARE @EID INT = IDENT_CURRENT('Z_ora_CRM_SaleOfferEntry')+1
SELECT 
	FID,@EID FEntryID,FSEQ,FMTLGROUP,FQTY,FPDTTEXT,NEWID() as FGUID
INTO #Temp
FROM ora_CRM_NicheEntry WHERE FID=@NFID
UPDATE #Temp SET FEntryID=FEntryID+FSEQ
SELECT @EID=MAX(FEntryID)+1 FROM #Temp
DBCC CHECKIDENT(Z_ora_CRM_SaleOfferEntry, RESEED, @EID)

INSERT INTO ora_CRM_SaleOfferEntry(
	FID,FEntryID,FSEQ,FMTLGROUP,FQTY,FDESCRIBE,FGUID
)
SELECT 
	@SFID,FEntryID,FSEQ,FMTLGROUP,FQTY,FPDTTEXT,FGUID
FROM #Temp

--持有记录
DECLARE @EID_H INT = IDENT_CURRENT('Z_ora_CRM_SaleOfferHode')+1
DBCC CHECKIDENT(Z_ora_CRM_SaleOfferHode, RESEED, @EID_H)
INSERT INTO ora_CRM_SaleOfferHode(
	FID,FHEntryID,FHSEQ,FHHDORGID,FHHDDEPT,FHHOLDER,FHSN,FHBEGDATE,FHENDDATE
)
SELECT @SFID,@EID_H,1,FCrmHdOrgID,FCrmHdDept,FCrmHolder,FCrmSN,GETDATE(),'9999-12-31'
FROM ora_CRM_Niche WHERE FID=@NFID

SELECT @SFID FID
END

-- exec proc_czly_GeneSaleOffer @NFID='100114'
--ALTER TABLE ora_CRM_CCRP ALTER COLUMN FPRJNAME NVARCHAR(255)
