-- 单位总经理设置
CREATE TABLE [dbo].[ora_OA_GManager](
	[FID] [int] IDENTITY(1,1) NOT NULL,
	[FORGID] [int] NULL,
	[FDEPTID] [int] NULL,
	[FGMANAGERID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[FID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

