-- 获取工作计划需要被通知的用户
CREATE PROC [dbo].[proc_czly_GetNeedNotifiedUsers]
AS
BEGIN
	SELECT t.FUSERID,t.FNAME,m.FOPENID FROM (
		SELECT FUSERID,FNAME,FLINKOBJECT FROM T_SEC_USER WHERE FFORBIDSTATUS='A' AND FLINKOBJECT<>0
		AND FUSERID NOT IN (
			SELECT FCREATORID FROM ora_Task_PersonalReport 
			WHERE YEAR(GETDATE())=YEAR(FCREATEDATE) AND MONTH(GETDATE())=MONTH(FCREATEDATE)
			AND FDOCUMENTSTATUS IN ('B', 'C')
		)
	) t
	INNER JOIN V_bd_ContactObject c ON c.FID=t.FLINKOBJECT
	INNER JOIN T_HR_EMPINFO e ON e.FNUMBER=c.FNUMBER
	INNER JOIN T_SEC_XTUSERMAP m on t.FUSERID=m.FUSERID
	WHERE e.FID NOT IN (SELECT DISTINCT FGMANAGERID FROM ora_OA_GManager)
END

-- exec proc_czly_GetNeedNotifiedUsers